version: "3.7"

services:
  db-entrega-sos-backend:
    container_name: db-entrega-sos-backend
    image: postgres:12.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/create-multiple-postgres-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgres-databases.sh
    networks: 
      - network-entrega-sos-backend
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  app-entrega-sos-backend:
    container_name: app-entrega-sos-backend
    build: .
    restart: always
    volumes:
      - .:/usr/src/project
    networks:
      - network-entrega-sos-backend
    ports:
      - "5000:5000"
    environment:
      - ENV_APP=${ENV_APP}
    depends_on:
      - db-entrega-sos-backend
  nginx-entrega-sos-backend:
    container_name: nginx-entrega-sos-backend
    image: nginx:1.16.1-alpine
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-entrega-sos-backend
    ports:
      - "80:80"
    depends_on:
      - app-entrega-sos-backend
      
volumes:
  postgres_data:
networks:
  network-entrega-sos-backend: