from flask import jsonify
from . import api_v1

bairros = [
	'35º BI',
	'Aeroporto',
	'Asa Branca',
	'Aviário',
	'Baraúnas',
	'Bonfim de Feira',
	'Brasília',
	'Calumbi',
	'Campo do Gado Novo',
	'Campo Limpo',
	'Capuchinhos',
	'Caseb',
	'Centro',
	'Chácara São Cosme',
	'Cidade Nova',
	'CIS',
	'Conceição I',
	'Conceição II',
	'Cruzeiro',
	'Feira IV',
	'Feira IX',
	'Feira IX (Expansão)',
	'Feira V',
	'Feira VI',
	'Feira VII',
	'Feira X',
	'Gabriela',
	'Governador João Durval Carneiro',
	'Humildes',
	'Jaguara',
	'Jaíba',
	'Jardim Acácia',
	'Jardim Cruzeiro',
	'Jussara',
	'Kalilândia',
	'Lagoa Grande',
	'Lagoa Salgada',
	'Limoeiro',
	'Mangabeira',
	'Maria Quitéria',
	'Matinha',
	'Muchila',
	'Nova Esperança',
	'Novo Horizonte',
	'Olhos D Água',
	'Pampalona',
	'Papagaio',
	'Parque Getúlio Vargas',
	'Parque Ipê',
	'Parque Viver',
	'Pedra do Descanso',
	'Pedra Ferrada',
	'Ponto Central',
	'Queimadinha',
	'Rocinha',
	'Rua Nova',
	'Santa Mônica',
	'Santo Antônio dos Prazeres',
	'São João',
	'Serraria Brasil',
	'SIM',
	'Sobradinho',
	'Subaé',
	'Tiquaruçu',
	'Tomba',
	'Vietnã',
	'Viveiros'
]


@api_v1.route('/bairros', methods=['GET'])
def get_all_bairros():
    return jsonify({'bairros': bairros})