"""empty message

Revision ID: 0248216ef8d7
Revises: 
Create Date: 2020-04-03 09:15:56.617280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0248216ef8d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('tipo_negocio', sa.String(), nullable=True),
    sa.Column('outro_negocio', sa.String(), nullable=True),
    sa.Column('meio_pagamento', sa.String(), nullable=True),
    sa.Column('dias_horarios', sa.String(), nullable=True),
    sa.Column('delivery', sa.Boolean(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_empresas_email'), 'empresas', ['email'], unique=True)
    op.create_index(op.f('ix_empresas_usuario'), 'empresas', ['usuario'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empresas_usuario'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_email'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
