"""empty message

Revision ID: 1da171b4158e
Revises: 
Create Date: 2020-03-23 00:34:33.299022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da171b4158e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(length=32), nullable=True),
    sa.Column('usuario', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('telefone', sa.String(length=16), nullable=True),
    sa.Column('whatsapp', sa.String(length=16), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('endereco', sa.String(length=64), nullable=True),
    sa.Column('bairro', sa.String(length=32), nullable=True),
    sa.Column('cidade', sa.String(length=32), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('tipo_negocio', sa.String(length=16), nullable=True),
    sa.Column('meio_pagamento', sa.String(length=32), nullable=True),
    sa.Column('dias_horarios', sa.String(length=128), nullable=True),
    sa.Column('delivery', sa.Boolean(), nullable=True),
    sa.Column('instagram', sa.String(length=64), nullable=True),
    sa.Column('facebook', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=64), nullable=True),
    sa.Column('obs', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_email'), 'empresas', ['email'], unique=True)
    op.create_index(op.f('ix_empresas_usuario'), 'empresas', ['usuario'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empresas_usuario'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_email'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
