"""empty message

Revision ID: b4e58b180cfe
Revises: 1da171b4158e
Create Date: 2020-03-23 10:13:22.197295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e58b180cfe'
down_revision = '1da171b4158e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('empresas', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'empresas', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empresas', type_='unique')
    op.drop_column('empresas', 'token_expiration')
    op.drop_column('empresas', 'token')
    # ### end Alembic commands ###
